# Generated by Django 4.1.3 on 2022-11-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("top_50", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата прогноза"),
        ),
    ]
