# Generated by Django 4.1.3 on 2022-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_50', '0002_alter_weather_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.FloatField(default=0, verbose_name='Температура в градусах Цельсия'),
        ),
    ]
