version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:alpine
    restart: always
    container_name: 'weather_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: weather_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    depends_on:
      - db
  celery:
    build: .
    container_name: weather_celery
    command: celery -A weather worker --loglevel=INFO
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    container_name: weather_beat
    command: celery -A weather beat -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web
volumes:
  db:
